#ProjectPhalconPHP/docker-compose.yml
version: '2'
services:
  php:
    build: ./php
    container_name: ProjectPhalconPHP_php
    ports:
    - '8081:80'
    volumes:
    - ./code:/var/www/html
    
  mysql:
    image: mysql:5.7.22
    container_name: ProjectPhalconPHP_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: docker
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql/backup:/backup
      - ./mysql/db:/var/lib/mysql    