<html>

<head>
    <code>PHP - Servicios RESTTT</code>
</head>

<body>
    <div class="form-group">
        <label for="nombre">Nombre</label>
        <div>
            <?php echo $this.tag->textField ?>
        </div>
    </div>

    <input type="button" name="Btn1" value="Buscar1" id="boton1" onclick="alert('Invocando evento')">
    <input type="button" name="Btn2" value="Buscar2" id="boton2" onclick="funcionTest()">
</body>

</html>